name: 'policy-compliance-scan'
description: 'Triggers compliance scan on Azure resources and fails/passes based on the compliance state of the resources'
inputs: 
  scopes: 
    description: 'TList of resource identifiers for which compliance scan will be triggered'
    required: true
  scopes-ignore:
    description: 'List of resource identifiers for which compliance results will be ignored. Action will continue irrespective of their compliance state'
    required: false
  report-name:
    description: 'Name of CSV file that contains the report of non-compliant resources. This is uploaded as an artifact in the workflow run'
    required: false
    default: policy-compliance-scan
  skip-report:
    description: 'Allows you to skip generation and upload of CSV file'
    required: false
    default: false
  wait:
    description: 'If set to true, the action will wait till the scan is complete and pass/fail based on the compliance state of resources. If set to false, the action will trigger compliance scan and immediately pass without waiting for scan completion'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'lib/run.js'
