name: 'AzPac'
description: 'Azure policy as code action'
inputs: 
  scopes: # id of input
    description: 'Scopes to perform scanning on'
    required: true
  ignore-result:
    description: 'List of resource identifiers for which compliance results will be ignored. Action will continue irrespective of their compliance state'
    required: false
  csv-name:
    description: 'Name of csv to be generated'
    required: false
    default: ScanResults
  skip-artifacts:
    description: 'To skip generation of csv artifact'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'lib/run.js'